version: '3.8'

services:

  database:
    container_name: database
    ports:
      - '5432:5432'
    image: postgres:14.7
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./chessapp_postgres:/var/lib/postgresql/data
    networks:
      chess_network:

  back:
    build:
      context: ./backend/
      dockerfile: ./docker/Dockerfile
    container_name: back
    ports:
      - '3000:3000'
      - '5555:5555'
    depends_on:
      - database
    volumes:
      - ./backend:/app
    networks:
      - chess_network

  front:
    build:
      context: ./frontend/
      dockerfile: ./docker/Dockerfile
    container_name: front
    ports:
      - '3001:3001'
    depends_on:
      - back
    volumes:
      - ./frontend:/app
    networks:
      - chess_network

networks:
  chess_network:
    name: chess_network