version: '3.8'

services:
  front:
    build:
      context: ./frontend/
      dockerfile: ./docker/Dockerfile
    container_name: front
    ports:
      - '3001:3001'
    volumes:
      - ./frontend:/app