version : "3.8"

services:
    database:
        container_name: database
        image: postgres:14.7
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - type: volume
              source: chessapp_postgres
              target: /var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
volumes:
    chessapp_postgres: